In [ ]:
import pandas as pd
import numpy as np
from vnstock import Quote

#Date
start_date = "2015-01-01"
end_date = "2026-04-04"

#Download data
quote = Quote(symbol="VN30", source= "KBS")
df_vn30 = quote.history(start=start_date, end=end_date, interval="d")

df_vn30["time"] = pd.to_datetime(df_vn30["time"])
df_vn30.set_index("time", inplace=True)

df_vn30

                     open  high   low  close     volume
time
2015-01-05 07:00:00  0.60  0.60  0.60   0.60   50120690
2015-01-06 07:00:00  0.59  0.61  0.59   0.61   44823080
2015-01-07 07:00:00  0.61  0.61  0.61   0.61   52993980
2015-01-08 07:00:00  0.61  0.61  0.61   0.61   35326680
2015-01-09 07:00:00  0.61  0.62  0.61   0.62   54770470
...                   ...   ...   ...    ...        ...
2026-03-27 07:00:00  1.79  1.83  1.79   1.82  280159239
2026-03-30 07:00:00  1.79  1.82  1.78   1.81  299904480
2026-03-31 07:00:00  1.82  1.83  1.81   1.83  323364851
2026-04-01 07:00:00  1.87  1.87  1.83   1.86  324883193
2026-04-02 07:00:00  1.86  1.86  1.84   1.85  349074165

[2804 rows x 5 columns]

#Feature engineering

In [ ]:
df_vn30["log_return"] = np.log(df_vn30["close"]/ df_vn30["close"].shift(1))

df_vn30["volatility"] = df_vn30["log_return"].rolling(window=14).std()

df_features = df_vn30.dropna(subset=["log_return", "volatility"]).copy()

df_features

                     open  high   low  close     volume  log_return  volatility
time
2015-01-23 07:00:00  0.61  0.62  0.61   0.62   43465530    0.016261    0.008725
2015-01-26 07:00:00  0.62  0.62  0.61   0.61   27978130   -0.016261    0.009020
2015-01-27 07:00:00  0.61  0.62  0.61   0.61   56520410    0.000000    0.009020
2015-01-28 07:00:00  0.61  0.61  0.61   0.61   42686560    0.000000    0.009020
2015-01-29 07:00:00  0.61  0.62  0.61   0.61   38860910    0.000000    0.007718
...                   ...   ...   ...    ...        ...         ...         ...
2026-03-27 07:00:00  1.79  1.83  1.79   1.82  280159239    0.016621    0.020363
2026-03-30 07:00:00  1.79  1.82  1.78   1.81  299904480   -0.005510    0.018266
2026-03-31 07:00:00  1.82  1.83  1.81   1.83  323364851    0.010989    0.016835
2026-04-01 07:00:00  1.87  1.87  1.83   1.86  324883193    0.016261    0.017023
2026-04-02 07:00:00  1.86  1.86  1.84   1.85  349074165   -0.005391    0.017023

[2790 rows x 7 columns]

In [ ]:
import os

# Create directory if it doesn't exist
os.makedirs("../data/processed", exist_ok=True)

# Save the DataFrame to a CSV file
df_features.to_csv("../data/processed/vn30_features.csv")